insert into student(id, firstname, lastname, email_address) values (11, 'student', 'one', 'one@school.ac.kr')
insert into student(id, firstname, lastname, email_address) values (12, 'student', 'two', 'two@school.ac.kr')
insert into student(id, firstname, lastname, email_address) values (13, 'student', 'three', 'three@school.ac.kr')
insert into student(id, firstname, lastname, email_address) values (14, 'student', 'four', 'four@school.ac.kr')
-- insert into student(id, firstname, lastname, email_address) values (15, 'student', 'five', 'five@school.ac.kr')